---
defaults:
 - _self_
 - data_info: DIV2K.yaml         # cifar10.yaml

#output_save_name: model_evaluation
output_save_name: eval_${data_info.data_name}_${chan_type}_${performance_metric} 
hydra:
  run:
    dir: outputs/${output_save_name} #${now:%Y-%m-%d_%H-%M-%S}

input_resolution: 0
chan_type: 'AWGN' #'AWGN', 'Rayleigh', 'none'
performance_metric: 'PSNR' #'PSNR', 'SSIM', 'MS-SSIM'
model_name: "ConvJSCC"
task_name: None
loss_name: 0 # MSE, CE, MSE_CE
#model_capacity: 32
SNR_info: 1 # 1,4,7,10, random
rcpp: 12
random_seed: 0
step_num: 2
visualize_img_num: 2
ratio: 0.5
gamma: 0.5
ratio1: 0.5
ratio2: 0.5